
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class12
 */
public class Level2 extends javax.swing.JFrame {

    /**
     * Creates new form Level2
     */
    public Level2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HaxField = new javax.swing.JTextField();
        BaitField = new javax.swing.JTextField();
        Field = new javax.swing.JTextField();
        Field1 = new javax.swing.JTextField();
        Field2 = new javax.swing.JTextField();
        Cat = new javax.swing.JLabel();
        Mouse = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        Chez1 = new javax.swing.JLabel();
        Chez = new javax.swing.JLabel();
        LeftButton = new javax.swing.JButton();
        DirectionField = new javax.swing.JTextField();
        DownButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        UpButton = new javax.swing.JButton();
        Trap1 = new javax.swing.JLabel();
        Trap2 = new javax.swing.JLabel();
        Trap3 = new javax.swing.JLabel();
        Bait = new javax.swing.JLabel();
        BaitButton = new javax.swing.JButton();
        Chez2 = new javax.swing.JLabel();
        Score = new javax.swing.JTextField();

        HaxField.setText("0");

        BaitField.setText("0");

        Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldActionPerformed(evt);
            }
        });

        Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        Cat.setBackground(new java.awt.Color(204, 204, 204));
        Cat.setForeground(new java.awt.Color(204, 204, 204));
        Cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cat.png"))); // NOI18N

        Mouse.setBackground(new java.awt.Color(255, 255, 255));
        Mouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smol Jerry.jpg"))); // NOI18N
        Mouse.setToolTipText("");
        Mouse.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MouseComponentShown(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 0, 51));
        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("X");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        Chez1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chez.png"))); // NOI18N

        Chez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chez.png"))); // NOI18N

        LeftButton.setText("Left");
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        DirectionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DirectionFieldMouseClicked(evt);
            }
        });
        DirectionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectionFieldActionPerformed(evt);
            }
        });
        DirectionField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DirectionFieldKeyTyped(evt);
            }
        });

        DownButton.setText("Down");
        DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButtonActionPerformed(evt);
            }
        });

        RightButton.setText("Right");
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });
        RightButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RightButtonKeyPressed(evt);
            }
        });

        UpButton.setText("Up");
        UpButton.setVerifyInputWhenFocusTarget(false);
        UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButtonActionPerformed(evt);
            }
        });
        UpButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpButtonKeyPressed(evt);
            }
        });

        Trap1.setBackground(new java.awt.Color(204, 0, 204));
        Trap1.setForeground(new java.awt.Color(204, 0, 204));
        Trap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traps.jpg"))); // NOI18N
        Trap1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 122, 87)));

        Trap2.setBackground(new java.awt.Color(204, 0, 204));
        Trap2.setForeground(new java.awt.Color(204, 0, 204));
        Trap2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traps.jpg"))); // NOI18N
        Trap2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 122, 87)));

        Trap3.setBackground(new java.awt.Color(204, 0, 204));
        Trap3.setForeground(new java.awt.Color(204, 0, 204));
        Trap3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Traps.jpg"))); // NOI18N
        Trap3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(185, 122, 87)));

        Bait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Placeholder.png"))); // NOI18N

        BaitButton.setText("Bait");
        BaitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaitButtonActionPerformed(evt);
            }
        });

        Chez2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chez.png"))); // NOI18N

        Score.setEditable(false);
        Score.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Score.setText("10000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Bait, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(206, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Chez1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Trap1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Trap3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(253, 253, 253)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(DownButton)
                                    .addGap(48, 48, 48))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DirectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(RightButton))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(304, 304, 304)
                            .addComponent(UpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Chez2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Trap2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Chez, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mouse, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(BaitButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ExitButton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(Bait, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Chez2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Trap1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Trap2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(Chez1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Chez, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DirectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(DownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BaitButton)
                                .addComponent(Mouse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Trap3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(BaitField.getText())==0)
        {
            BaitButton.setEnabled(true);
        }
        int score=Integer.parseInt(Score.getText());
        int nscore= score-10;
        Score.setText(""+nscore);
        int hax=Integer.parseInt(HaxField.getText());
        int ri= Mouse.getX();
        int y= Mouse.getY();
        int xchez= Chez.getX();
        int ychez= Chez.getY();
        int n= ri-10;
        Mouse.setLocation(n, y);
        System.out.println("Location: ");
        System.out.println("X: "+ n);
        System.out.println("Y: "+ y);
        System.out.println(" ");
        if(y>=383 && y<=563)
        {
            if(n>=616 && n<=816)
            {
                Chez.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field.setText("1");
            }
        }
        if(y>=263 && y<=433)
        {
            if(n>=136 && n<=326)
            {
                Chez1.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field1.setText("1");
            }
        }
        if(y>=-47 && y<=123)
        {
            if(n>=606 && n<=806)
            {
                Chez2.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field2.setText("1");
            }
        }        
        if(n<=-114)
        {
            Mouse.setLocation(916, y);
            hax++;
        }
        if(n>=916)
        {
            Mouse.setLocation(-114, y);
            hax++;
        }
        if(y<=-126)
        {
            Mouse.setLocation(n, 794 );
            hax++;
        }
        if(y>=794)
        {
            Mouse.setLocation(n, -126 );
            hax++;
        }
        if(hax==5)
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
            JOptionPane.showMessageDialog(null, "Don't cheat.");
            System.exit(0);
        }
        if(
                ((n>=266 && n<=496) && (y>=373 && y<=583)) || 
                ((n>=106 && n<=336) && (y>=53 && y<=263)) || 
                ((n>=606 && n<=826) && (y>=63 && y<=263))  
          )
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                this.dispose();
        }
        if(Field1.getText().equals("1") && Field.getText().equals("1") && Field2.getText().equals("1"))
        {
            JOptionPane.showMessageDialog(null, "You win.");
            JOptionPane.showMessageDialog(null, "Your score is "+nscore);
            System.exit(0);
        }
        HaxField.setText(""+hax);
        int mx= Mouse.getX();
        int my= Mouse.getY();
        int cx= Cat.getX();
        int cy= Cat.getY();
        int bx=Bait.getX();
        int by=Bait.getY();
        int bait=Integer.parseInt(BaitField.getText());
        System.out.println("Bait: "+bait);
        if(bait!=0)
        {
            if((bx>cx-20&& bx<cx+20) && (by>cy-20 && by<cy+20))
            {
                bait--;
                BaitField.setText(""+bait);
                if(bait==0)
                {
                    Bait.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Placeholder.png"));
                }
            }
            else
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-bx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-by;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
        }
        else
        {
            if(cx!=mx || cy!=my)
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-mx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-my;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
            if((mx>cx-60&& mx<cx+60) && (my>cy-60 && my<cy+60))
            {
                Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                 new Menu().setVisible(true);
                 this.dispose();
            }
        }
     
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void DirectionFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DirectionFieldMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_DirectionFieldMouseClicked

    private void DirectionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectionFieldActionPerformed
        // TODO add your handling code here:
        String dir= DirectionField.getText();
        if(dir.equals("w") || dir.equals("W"))
        {
            UpButton.doClick();
        }
        else if(dir.equals("s") || dir.equals("S"))
        {
            DownButton.doClick();
        }
        else if(dir.equals("a") || dir.equals("A"))
        {
            LeftButton.doClick();
        }
        else if(dir.equals("d") || dir.equals("D"))
        {
            RightButton.doClick();
        }
        else if(dir.equals("b") || dir.equals("B"))
        {
            if(Integer.parseInt(BaitField.getText())==0)
            {
              BaitButton.doClick();   
            }                    
        }    
        DirectionField.setText("");
    }//GEN-LAST:event_DirectionFieldActionPerformed

    private void DirectionFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DirectionFieldKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_DirectionFieldKeyTyped

    private void DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButtonActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(BaitField.getText())==0)
        {
            BaitButton.setEnabled(true);
        }
        int score=Integer.parseInt(Score.getText());
        int nscore= score-10;
        Score.setText(""+nscore);
        int hax=Integer.parseInt(HaxField.getText());
        int ri= Mouse.getX();
        int y= Mouse.getY();
        int xchez= Chez.getX();
        int ychez= Chez.getY();
        int y1= y+10;
        Mouse.setLocation(ri, y1);
        System.out.println("Location: ");
        System.out.println("X: "+ ri);

        System.out.println("Y: "+ y1);
        System.out.println(" ");
        if(y1>=383 && y1<=563)
        {
            if(ri>=616 && ri<=816)
            {
                Chez.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field.setText("1");
            }
        }
        if(y1>=263 && y1<=433)
        {
            if(ri>=136 && ri<=326)
            {
                Chez1.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field1.setText("1");
            }
        }
        if(y1>=-47 && y1<=123)
        {
            if(ri>=606 && ri<=806)
            {
                Chez2.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field2.setText("1");
            }
        }
        if(ri<=-114)
        {
            Mouse.setLocation(916, y1);
            hax++;
        }
        if(ri>=916)
        {
            Mouse.setLocation(-114, y1);
            hax++;
        }
        if(y1<=-126)
        {
            Mouse.setLocation(ri, 794 );
            hax++;
        }
        if(y1>=794)
        {
            Mouse.setLocation(ri, -126 );
            hax++;
        }
        if(hax==5)
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
            JOptionPane.showMessageDialog(null, "Don't cheat.");
            System.exit(0);
        }
        if(
                ((ri>=266 && ri<=496) && (y1>=373 && y1<=583)) || 
                ((ri>=106 && ri<=336) && (y1>=53 && y1<=263)) || 
                ((ri>=606 && ri<=826) && (y1>=63 && y1<=263))  
          )
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                new Menu().setVisible(true);
                this.dispose();
        }
        if(Field1.getText().equals("1") && Field.getText().equals("1") && Field2.getText().equals("1"))
        {
            JOptionPane.showMessageDialog(null, "You win.");
            JOptionPane.showMessageDialog(null, "Your score is "+nscore);
            System.exit(0);
        }
        HaxField.setText(""+hax);
        int mx= Mouse.getX();
        int my= Mouse.getY();
        int cx= Cat.getX();
        int cy= Cat.getY();
        int bx=Bait.getX();
        int by=Bait.getY();
        int bait=Integer.parseInt(BaitField.getText());
        System.out.println("Bait: "+bait);
        if(bait!=0)
        {
            if((bx>cx-20&& bx<cx+20) && (by>cy-20 && by<cy+20))
            {
                bait--;
                BaitField.setText(""+bait);
                if(bait==0)
                {
                    Bait.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Placeholder.png"));
                }
            }
            else
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-bx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-by;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
        }
        else
        {
            if(cx!=mx || cy!=my)
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-mx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-my;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
            if((mx>cx-60&& mx<cx+60) && (my>cy-60 && my<cy+60))
            {
                Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                new Menu().setVisible(true);
                 this.dispose();
            }
        }

    }//GEN-LAST:event_DownButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(BaitField.getText())==0)
        {
            BaitButton.setEnabled(true);
        }
        int score=Integer.parseInt(Score.getText());
        int nscore= score-10;
        Score.setText(""+nscore);
        int hax= Integer.parseInt(HaxField.getText());
        int ri= Mouse.getX();
        int y= Mouse.getY();
        int xchez= Chez.getX();
        int ychez= Chez.getY();
        int n= ri+10;
        Mouse.setLocation(n, y);
        System.out.println("Location: ");
        System.out.println("X: "+ n);

        System.out.println("Y: "+ y);
        System.out.println(" ");
        
        if(y>=383 && y<=563)
        {
            if(n>=616 && n<=816)
            {
                Chez.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field.setText("1");
            }
        }
        if(y>=263 && y<=433)
        {
            if(n>=136 && n<=326)
            {
                Chez1.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field1.setText("1");
            }
        }
        if(y>=-47 && y<=123)
        {
            if(n>=606 && n<=806)
            {
                Chez2.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field2.setText("1");
            }
        }
        if(n<=-114)
        {
            Mouse.setLocation(916, y);
            hax++;
        }
        if(n>=916)
        {
            Mouse.setLocation(-114, y);
            hax++;
        }
        if(y<=-126)
        {
            Mouse.setLocation(n, 794 );
            hax++;
        }
        if(y>=794)
        {
            Mouse.setLocation(n, -126 );
            hax++;
        }
        if(hax==5)
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
            JOptionPane.showMessageDialog(null, "Don't cheat.");
            System.exit(0);
        }
        if(
                ((n>=266 && n<=496) && (y>=373 && y<=583)) || 
                ((n>=106 && n<=336) && (y>=53 && y<=263)) || 
                ((n>=606 && n<=826) && (y>=63 && y<=263))  
          )
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                new Menu().setVisible(true);
                this.dispose();
        }
        if(Field1.getText().equals("1") && Field.getText().equals("1") && Field2.getText().equals("1"))
        {
            JOptionPane.showMessageDialog(null, "You win.");
            JOptionPane.showMessageDialog(null, "Your score is "+nscore);
            System.exit(0);
        }
        HaxField.setText(""+hax);
        int mx= Mouse.getX();
        int my= Mouse.getY();
        int cx= Cat.getX();
        int cy= Cat.getY();
        int bx=Bait.getX();
        int by=Bait.getY();
        int bait=Integer.parseInt(BaitField.getText());
        System.out.println("Bait: "+bait);
        if(bait!=0)
        {
            if((bx>cx-20&& bx<cx+20) && (by>cy-20 && by<cy+20))
            {
                bait--;
                BaitField.setText(""+bait);
                if(bait==0)
                {
                    Bait.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Placeholder.png"));
                }
            }
            else
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-bx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-by;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
        }
        else
        {
            if(cx!=mx || cy!=my)
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-mx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-my;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
            if((mx>cx-60&& mx<cx+60) && (my>cy-60 && my<cy+60))
            {
                Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                new Menu().setVisible(true);
                 this.dispose();
            }
        }
        
    }//GEN-LAST:event_RightButtonActionPerformed

    private void RightButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RightButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RightButtonKeyPressed

    private void UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButtonActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(BaitField.getText())==0)
        {
            BaitButton.setEnabled(true);
        }
        int score=Integer.parseInt(Score.getText());
        int nscore= score-10;
        Score.setText(""+nscore);
        int hax=Integer.parseInt(HaxField.getText());
        int ri= Mouse.getX();
        int y= Mouse.getY();
        int xchez= Chez.getX();
        int ychez= Chez.getY();
        int y1= y-10;
        Mouse.setLocation(ri, y1);
        System.out.println("Location: ");
        System.out.println("X: "+ ri);

        System.out.println("Y: "+ y1);
        System.out.println(" ");
        

        if(y1>=383 && y1<=563)
        {
            if(ri>=616 && ri<=816)
            {
                Chez.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field.setText("1");
            }
        }
        if(y1>=263 && y1<=433)
        {
            if(ri>=136 && ri<=326)
            {
                Chez1.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field1.setText("1");
            }
        }
        if(y1>=-47 && y1<=123)
        {
            if(ri>=606 && ri<=806)
            {
                Chez2.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Eaten Chez.png"));
                Field2.setText("1");
            }
        }
        
        if(ri<=-114)
        {
            Mouse.setLocation(916, y1);
            hax++;
        }
        if(ri>=916)
        {
            Mouse.setLocation(-114, y1);
            hax++;
        }
        if(y1<=-126)
        {
            Mouse.setLocation(ri, 794 );
            hax++;
        }
        if(y1>=794)
        {
            Mouse.setLocation(ri, -126 );
            hax++;
        }
        if(hax==5)
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
            JOptionPane.showMessageDialog(null, "Don't cheat.");
            System.exit(0);
        }
        if(
                ((ri>=266 && ri<=496) && (y1>=373 && y1<=583)) || 
                ((ri>=106 && ri<=336) && (y1>=53 && y1<=263)) || 
                ((ri>=606 && ri<=826) && (y1>=63 && y1<=263))  
          )
        {
            Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                new Menu().setVisible(true);
                this.dispose();
        }
        if(Field1.getText().equals("1") && Field.getText().equals("1") && Field2.getText().equals("1"))
        {
            JOptionPane.showMessageDialog(null, "You win.");
            JOptionPane.showMessageDialog(null, "Your score is "+nscore);
            System.exit(0);
        }
        HaxField.setText(""+hax);
        int mx= Mouse.getX();
        int my= Mouse.getY();
        int cx= Cat.getX();
        int cy= Cat.getY();
        int bx=Bait.getX();
        int by=Bait.getY();
        int bait=Integer.parseInt(BaitField.getText());
        System.out.println("Bait: "+bait);
        if(bait!=0)
        {
            if((bx>cx-20&& bx<cx+20) && (by>cy-20 && by<cy+20))
            {
                bait--;
                BaitField.setText(""+bait);
                if(bait==0)
                {
                    Bait.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Placeholder.png"));
                }
            }
            else
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-bx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-by;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
        }
        else
        {
            if(cx!=mx || cy!=my)
            {
                int difx=0;
                int dify=0;
                int firstdifx=cx-mx;
                if(firstdifx<0)
                {
                    difx= firstdifx * (-1);
                }
                else
                {
                    difx= firstdifx ;
                }
                int firstdify=cy-my;
                if(firstdify<0)
                {
                    dify= firstdify * (-1);
                }
                else
                {
                    dify= firstdify;
                }
                if(difx>dify)
                {
                    if(firstdifx>0)
                    {
                        Cat.setLocation(cx-15, cy);
                    }
                    else
                    {
                        Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<=dify)
                {
                    if(firstdify>0)
                    {
                        Cat.setLocation(cx,cy-15);
                    }
                    else
                    {
                        Cat.setLocation(cx,cy+15);
                    }
                }
            }
            if((mx>cx-60&& mx<cx+60) && (my>cy-60 && my<cy+60))
            {
                Mouse.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Lose Jerry.jpg"));
                for(long che=1; che!=500000000; che++)
                {
                    ;
                }
                JOptionPane.showMessageDialog(null, "Ha. You lose.");
                JOptionPane.showMessageDialog(null, "Git gud. GGEZ");
                new Menu().setVisible(true);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_UpButtonActionPerformed

    private void UpButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpButtonKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_UpButtonKeyPressed

    private void BaitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaitButtonActionPerformed
        // TODO add your handling code here:

        int mx= Mouse.getX();
        int my= Mouse.getY();
        Bait.setIcon(new ImageIcon("C:\\Users\\Pranav\\Documents\\CatAndMouse\\CatAndMouse\\src\\Bait.png"));
        Bait.setLocation(mx, my);

        if(Integer.parseInt(BaitField.getText())==0)
        {
            BaitField.setText("5");
        }
        if(Integer.parseInt(BaitField.getText())!=0)
        {
            BaitButton.setEnabled(false);
        }
        int score=Integer.parseInt(Score.getText());
        int nscore= score-100;
        Score.setText(""+nscore);
    }//GEN-LAST:event_BaitButtonActionPerformed

    private void Field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field2ActionPerformed

    private void FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldActionPerformed

    private void MouseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MouseComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_MouseComponentShown

    private void HoldMechanism () {
       int timecheck=0;
       for( ; timecheck<500; timecheck++ )
       {
           if(DirectionField.getText()=="")
           {
            ;
           }
           else
           {
                String dir= DirectionField.getText();
                if(dir.equals("w") || dir.equals("W"))
                {
                    UpButton.doClick();
                }
                else if(dir.equals("s") || dir.equals("S"))
                {
                    DownButton.doClick();
                }   
                else if(dir.equals("a") || dir.equals("A"))
                {
                    LeftButton.doClick();
                }
                else if(dir.equals("d") || dir.equals("D"))
                {
                    RightButton.doClick();
                }
                else if(dir.equals("b") || dir.equals("B"))
                {
                    if(Integer.parseInt(BaitField.getText())==0)
                    {
                        BaitButton.doClick();   
                    }                    
                }    
            DirectionField.setText("");
           }
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bait;
    private javax.swing.JButton BaitButton;
    private javax.swing.JTextField BaitField;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Chez;
    private javax.swing.JLabel Chez1;
    private javax.swing.JLabel Chez2;
    private javax.swing.JTextField DirectionField;
    private javax.swing.JButton DownButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField Field;
    private javax.swing.JTextField Field1;
    private javax.swing.JTextField Field2;
    private javax.swing.JTextField HaxField;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel Mouse;
    private javax.swing.JButton RightButton;
    private javax.swing.JTextField Score;
    private javax.swing.JLabel Trap1;
    private javax.swing.JLabel Trap2;
    private javax.swing.JLabel Trap3;
    private javax.swing.JButton UpButton;
    // End of variables declaration//GEN-END:variables
}
