
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class11
 */
public class Level1 extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public Level1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Field = new javax.swing.JTextField();
        Field1 = new javax.swing.JTextField();
        HaxField = new javax.swing.JTextField();
        BaitField = new javax.swing.JTextField();
        BufferField = new javax.swing.JTextField();
        KeyField = new javax.swing.JTextField();
        MoveButton = new javax.swing.JButton();
        LeftButton = new javax.swing.JButton();
        DownButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        UpButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        BaitButton = new javax.swing.JButton();
        DirectionField = new javax.swing.JTextField();
        Cat = new javax.swing.JLabel();
        Bait = new javax.swing.JLabel();
        Mouse = new javax.swing.JLabel();
        Chez1 = new javax.swing.JLabel();
        Chez = new javax.swing.JLabel();
        ScoreField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        HaxField.setText("0");

        BaitField.setText("0");

        MoveButton.setText("B");
        MoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 460));
        setMinimumSize(new java.awt.Dimension(943, 423));
        setPreferredSize(new java.awt.Dimension(950, 460));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        LeftButton.setText("◄");
        LeftButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LeftButton.setContentAreaFilled(false);
        LeftButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LeftButton);
        LeftButton.setBounds(790, 330, 54, 46);

        DownButton.setText("▼");
        DownButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DownButton.setContentAreaFilled(false);
        DownButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DownButton);
        DownButton.setBounds(840, 380, 54, 46);

        RightButton.setText("►");
        RightButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RightButton.setContentAreaFilled(false);
        RightButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });
        RightButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RightButtonKeyPressed(evt);
            }
        });
        getContentPane().add(RightButton);
        RightButton.setBounds(890, 330, 54, 46);

        UpButton.setText("▲");
        UpButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpButton.setContentAreaFilled(false);
        UpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpButton.setMaximumSize(new java.awt.Dimension(13, 17));
        UpButton.setMinimumSize(new java.awt.Dimension(13, 17));
        UpButton.setPreferredSize(new java.awt.Dimension(13, 17));
        UpButton.setVerifyInputWhenFocusTarget(false);
        UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButtonActionPerformed(evt);
            }
        });
        UpButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpButtonKeyPressed(evt);
            }
        });
        getContentPane().add(UpButton);
        UpButton.setBounds(840, 280, 54, 46);

        ExitButton.setBackground(new java.awt.Color(255, 0, 51));
        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("X");
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(899, 0, 47, 37);

        BaitButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        BaitButton.setText("Bait");
        BaitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BaitButton.setContentAreaFilled(false);
        BaitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BaitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BaitButton);
        BaitButton.setBounds(10, 400, 70, 30);

        DirectionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DirectionFieldMouseClicked(evt);
            }
        });
        DirectionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectionFieldActionPerformed(evt);
            }
        });
        DirectionField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DirectionFieldKeyTyped(evt);
            }
        });
        getContentPane().add(DirectionField);
        DirectionField.setBounds(917, 204, 29, 20);

        Cat.setBackground(new java.awt.Color(204, 204, 204));
        Cat.setForeground(new java.awt.Color(204, 204, 204));
        Cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cat.png"))); // NOI18N
        getContentPane().add(Cat);
        Cat.setBounds(201, 144, 139, 114);

        Bait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Placeholder.png"))); // NOI18N
        getContentPane().add(Bait);
        Bait.setBounds(940, 130, 100, 64);

        Mouse.setBackground(new java.awt.Color(255, 255, 255));
        Mouse.setToolTipText("");
        getContentPane().add(Mouse);
        Mouse.setBounds(390, 250, 149, 140);

        Chez1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chez.png"))); // NOI18N
        getContentPane().add(Chez1);
        Chez1.setBounds(62, 34, 137, 92);

        Chez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chez.png"))); // NOI18N
        getContentPane().add(Chez);
        Chez.setBounds(678, 69, 137, 92);

        ScoreField.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        ScoreField.setForeground(new java.awt.Color(255, 51, 0));
        ScoreField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreField.setText("15000");
        ScoreField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(ScoreField);
        ScoreField.setBounds(390, 10, 160, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wooden Floor.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formKeyPressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formFocusGained

    private void RightButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RightButtonKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RightButtonKeyPressed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        // TODO add your handling code here:       
        KeyField.setText("D");
        MoveButton.doClick();
    }//GEN-LAST:event_RightButtonActionPerformed

    private void DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButtonActionPerformed
        // TODO add your handling code here:
        KeyField.setText("S");
        MoveButton.doClick();
    
    }//GEN-LAST:event_DownButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        // TODO add your handling code here:
        KeyField.setText("A");
        MoveButton.doClick();
        
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void UpButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpButtonKeyPressed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_UpButtonKeyPressed

    private void UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButtonActionPerformed
        // TODO add your handling code here:
        KeyField.setText("W");
        MoveButton.doClick();
        
    }//GEN-LAST:event_UpButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseEntered

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        String[] pizzas = {"Yes", "No"};
        JFrame frame = new JFrame("Input Dialog Example 3");
        String favoritePizza = (String) JOptionPane.showInputDialog(frame, 
        "Do you want to quit?",
        "Favorite Pizza",
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        pizzas, 
        pizzas[0]);
        if(favoritePizza.matches("Yes"))
        {   new Menu().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BaitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaitButtonActionPerformed
        // TODO add your handling code here:
        int score= Integer.parseInt(ScoreField.getText());
        if(score>=1000)
        {   int mx= Mouse.getX();
            int my= Mouse.getY();
            Bait.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Bait.png"));
            Bait.setLocation(mx, my);
            if(Integer.parseInt(BaitField.getText())==0)
            {   BaitField.setText("5");
            }
            if(Integer.parseInt(BaitField.getText())!=0)
            {   BaitButton.setEnabled(false);
            }
            if(Integer.parseInt(BaitField.getText())==0)
            {   BaitButton.setEnabled(true);
            }
        }        
        if(score>1000)
        {   score=score-1000;
            if(score<1000)
            {   BaitButton.setEnabled(false);
            }
        }
        else
        {   score=0;
        }
        ScoreField.setText(""+score);
        
    }//GEN-LAST:event_BaitButtonActionPerformed
    
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formKeyTyped

    private void DirectionFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DirectionFieldKeyTyped
        // TODO add your handling code here:
     
    }//GEN-LAST:event_DirectionFieldKeyTyped

    private void DirectionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectionFieldActionPerformed
        // TODO add your handling code here:
        String dir= DirectionField.getText();
        if(dir.equals("w") || dir.equals("W"))
        {   UpButton.doClick();
        }
        else if(dir.equals("s") || dir.equals("S"))
        {   DownButton.doClick();
        }
        else if(dir.equals("a") || dir.equals("A"))
        {   LeftButton.doClick();
        }
        else if(dir.equals("d") || dir.equals("D"))
        {   RightButton.doClick();
        }
        else if(dir.equals("b") || dir.equals("B"))
        {   if(Integer.parseInt(BaitField.getText())==0)
            {   BaitButton.doClick();
            }
        }
        DirectionField.setText("");
        
    }//GEN-LAST:event_DirectionFieldActionPerformed

    private void DirectionFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DirectionFieldMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_DirectionFieldMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from CurrentUser;";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {    BufferField.setText(rs.getString("MouseID"));                                                   
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }        
        String user=BufferField.getText();        
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from LoginForm where MouseID='"+user+"';";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {   int skin=rs.getInt("skin");
                switch(skin)
                {   case 1: Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\smol Jerry.jpg"));
                    break;
                    case 2: Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Cool Jerry.png"));
                    break;
                    case 3: Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Slim.png"));
                    break;
                    default: Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\smol Jerry.jpg"));
                }                                                     
           }
           rs.close();
           stmt.close();
           con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void MoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveButtonActionPerformed
        // TODO add your handling code here:
        int y=0;
        int n=0;
        if(Integer.parseInt(BaitField.getText())==0)
        {   BaitButton.setEnabled(true);
        } 
        int score= Integer.parseInt(ScoreField.getText());
        if(score>100)
        {   score=score-100;
            if(score<1000)
            {   BaitButton.setEnabled(false);
            }
        }
        else
        {   score=0;
        }
        ScoreField.setText(""+score);
        int hax=Integer.parseInt(HaxField.getText());
        int ri= Mouse.getX();
        int y1= Mouse.getY();
        int xchez= Chez.getX();
        int ychez= Chez.getY();
        String dir=KeyField.getText();
        if(dir.matches("W"))
        {   n= ri;
            y=y1-10;
        }
        else if(dir.matches("A"))
        {   n= ri-10;
            y=y1;
        }
        else if(dir.matches("S"))
        {   n= ri;
            y=y1+10;
        }
        else if(dir.matches("D"))
        {   n= ri+10;
            y=y1;
        }
        Mouse.setLocation(n, y);
        System.out.println("Location: ");
        System.out.println("X: "+ n);
        System.out.println("Y: "+ y);
        System.out.println(" ");
        if(y>=-39 && y<=161)
        {   if(n>=542 && n<=812)
            {   Chez.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Eaten Chez.png"));
                Field.setText("1");
            }
        }
        if(y>=-89 && y<=121)
        {   if(n>=-38 && n<=192)
            {   Chez1.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Eaten Chez.png"));
                Field1.setText("1");
            }
        }
        if(n<=-148)
        {   Mouse.setLocation(932, y);
            hax++;
        }
        if(n>=942)
        {   Mouse.setLocation(-138, y);
            hax++;
        }
        if(y<=-129)
        {   Mouse.setLocation(n, 411 );
            hax++;
        }
        if(y>=431)
        {   Mouse.setLocation(n, -109 );
            hax++;
        }
        if(hax==10)
        {   Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Sad Jerry.jpg")); 
            JOptionPane.showMessageDialog(null, "Don't cheat.");
            System.exit(0);
        }
        if(Field1.getText().equals("1") && Field.getText().equals("1") )
        {   JOptionPane.showMessageDialog(null, "You win.");
            JOptionPane.showMessageDialog(null, "Your score is "+score+ ".");
            String user=BufferField.getText();
            try
            {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
                Statement stmt = con.createStatement();
                String bhai= "update LoginForm set Points = Points + "+score+" where MouseID = '"+user+"';";
                stmt.executeUpdate(bhai);                
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e);
            }    
            new Menu().setVisible(true);
            this.dispose();
        }
        HaxField.setText(""+hax);
        int mx= Mouse.getX();
        int my= Mouse.getY();
        int cx= Cat.getX();
        int cy= Cat.getY();
        int bx=Bait.getX();
        int by=Bait.getY();
        int bait=Integer.parseInt(BaitField.getText());
        System.out.println("Bait: "+bait);
        if(bait!=0)
        {   if((bx>cx-20&& bx<cx+20) && (by>cy-20 && by<cy+20))
            {   bait--;
                BaitField.setText(""+bait);
                if(bait==0)
                {   Bait.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Placeholder.png"));
                    Bait.setLocation(940, 130); 
                }
            }
            else
            {   int difx=0;
                int dify=0;        
                int firstdifx=cx-bx;
                if(firstdifx<0)
                {   difx= firstdifx * (-1);
                }
                else
                {   difx= firstdifx ;
                }
                int firstdify=cy-by;
                if(firstdify<0)
                {   dify= firstdify * (-1);
                }
                else
                {   dify= firstdify;
                }
                if(difx>dify)
                {   if(firstdifx>0)
                    {   Cat.setLocation(cx-15, cy);
                    }
                    else
                    {   Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<dify)
                {   if(firstdify>0)
                    {   Cat.setLocation(cx,cy-15);
                    }
                    else 
                    {   Cat.setLocation(cx,cy+15);
                    }
                }   
            }
        }
        else
        {   if(cx!=mx || cy!=my)
            {
                int difx=0;
                int dify=0;        
                int firstdifx=cx-mx;
                if(firstdifx<0)
                {   difx= firstdifx * (-1);
                }
                else
                {   difx= firstdifx ;
                }
                int firstdify=cy-my;
                if(firstdify<0)
                {   dify= firstdify * (-1);
                }
                else
                {   dify= firstdify;
                }
                if(difx>dify)
                {   if(firstdifx>0)
                    {   Cat.setLocation(cx-15, cy);
                    }
                    else
                    {   Cat.setLocation(cx+15,cy);
                    }
                }
                else if(difx<dify)
                {   if(firstdify>0)
                    {   Cat.setLocation(cx,cy-15);
                    }
                    else 
                    {   Cat.setLocation(cx,cy+15);
                    }
                }
            }
            if((mx>cx-60&& mx<cx+60) && (my>cy-60 && my<cy+60))
            {   Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Sad Jerry.jpg")); 
                for(long che=1; che!=500000000; che++)
                {   ;
                }
                JOptionPane.showMessageDialog(null, "You lose.");
                JOptionPane.showMessageDialog(null, "Better luck next time.");
                new Menu().setVisible(true);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_MoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bait;
    private javax.swing.JButton BaitButton;
    private javax.swing.JTextField BaitField;
    private javax.swing.JTextField BufferField;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Chez;
    private javax.swing.JLabel Chez1;
    private javax.swing.JTextField DirectionField;
    private javax.swing.JButton DownButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField Field;
    private javax.swing.JTextField Field1;
    private javax.swing.JTextField HaxField;
    private javax.swing.JTextField KeyField;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel Mouse;
    private javax.swing.JButton MoveButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JLabel ScoreField;
    private javax.swing.JButton UpButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
