/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class12
 */
public class LevelSelect extends javax.swing.JFrame {

    /**
     * Creates new form LevelSelect
     */
    public LevelSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Level1Button = new javax.swing.JButton();
        Level2Button = new javax.swing.JButton();
        Level3Button = new javax.swing.JButton();
        MenuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(415, 440));
        setPreferredSize(new java.awt.Dimension(415, 440));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 252, 252));
        jLabel1.setText("LevelSelect");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(128, 11, 151, 41);

        Level1Button.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        Level1Button.setForeground(new java.awt.Color(153, 255, 255));
        Level1Button.setText("1");
        Level1Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        Level1Button.setContentAreaFilled(false);
        Level1Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Level1Button);
        Level1Button.setBounds(97, 96, 209, 33);

        Level2Button.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        Level2Button.setForeground(new java.awt.Color(153, 255, 255));
        Level2Button.setText("2");
        Level2Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        Level2Button.setContentAreaFilled(false);
        Level2Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level2ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Level2Button);
        Level2Button.setBounds(97, 177, 209, 33);

        Level3Button.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        Level3Button.setForeground(new java.awt.Color(153, 255, 255));
        Level3Button.setText("3");
        Level3Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 2));
        Level3Button.setContentAreaFilled(false);
        Level3Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level3ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Level3Button);
        Level3Button.setBounds(97, 258, 209, 33);

        MenuButton.setBackground(new java.awt.Color(252, 252, 252));
        MenuButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(252, 252, 252));
        MenuButton.setText("MainMenu");
        MenuButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 252, 252), 2));
        MenuButton.setContentAreaFilled(false);
        MenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MenuButton);
        MenuButton.setBounds(97, 341, 209, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue_polygonal_background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Level1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level1ButtonActionPerformed
        // TODO add your handling code here:
        new Level1().setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_Level1ButtonActionPerformed

    private void Level2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level2ButtonActionPerformed
        // TODO add your handling code here:
        new Level2().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Level2ButtonActionPerformed

    private void Level3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level3ButtonActionPerformed
        // TODO add your handling code here:
        new Level3().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Level3ButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
                 this.dispose();
    }//GEN-LAST:event_MenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Level1Button;
    private javax.swing.JButton Level2Button;
    private javax.swing.JButton Level3Button;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
