
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class12
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        GoButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        NewButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(476, 290));
        setPreferredSize(new java.awt.Dimension(476, 290));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(205, 49, 49));
        jLabel1.setText("MouseLogin ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(137, 11, 173, 40);

        NameField.setBackground(new java.awt.Color(0, 159, 118));
        NameField.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        NameField.setForeground(new java.awt.Color(205, 49, 49));
        NameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 118)));
        NameField.setOpaque(false);
        getContentPane().add(NameField);
        NameField.setBounds(220, 78, 210, 28);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("MouseName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 79, 83, 21);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("MousePass");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 135, 75, 21);

        GoButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        GoButton.setForeground(new java.awt.Color(205, 49, 49));
        GoButton.setText("Lesgo.");
        GoButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 49, 49), 2));
        GoButton.setContentAreaFilled(false);
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoButton);
        GoButton.setBounds(10, 190, 209, 40);

        PasswordField.setBackground(new java.awt.Color(0, 159, 118));
        PasswordField.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(205, 49, 49));
        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 159, 118)));
        PasswordField.setOpaque(false);
        getContentPane().add(PasswordField);
        PasswordField.setBounds(220, 134, 210, 29);

        NewButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        NewButton.setForeground(new java.awt.Color(205, 49, 49));
        NewButton.setText("Create New Account");
        NewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(205, 49, 49), 2));
        NewButton.setContentAreaFilled(false);
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewButton);
        NewButton.setBounds(230, 190, 210, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark-green-polygonal-background.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 460, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        // TODO add your handling code here:
        String user= NameField.getText();
        String pass= new String(PasswordField.getPassword());
        int test=0;
        int best=0;
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String query= "select * from LoginForm;";
            ResultSet rs= stmt.executeQuery(query);
            String name, word;
            while (rs.next())
           {    name= rs.getString("MouseID");
                word= rs.getString("MousePass");
                if(name.compareTo(user)== 0)
                {   best=1; 
                    if(word.compareTo(pass) == 0)
                    {   JOptionPane.showMessageDialog(null, "Understandable. Have a nice time.");  
                        test=1; 
                        new Menu().setVisible(true);
                        this.dispose();                       
                    }
                    else
                    {   JOptionPane.showMessageDialog(null, "Incomprehensible. Have an awful time.");
                    }
                }
           }
           if(best==0)
           {    JOptionPane.showMessageDialog(null, "Who are you? Create an account.");
           }     
           if(test==1)
           {    String yaboi="insert into CurrentUser values('"+user+"');";
                stmt.executeUpdate(yaboi);
           }
           rs.close();
           stmt.close();
           con.close();                      
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
                
    }//GEN-LAST:event_GoButtonActionPerformed

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);
        this.dispose();  
        
    }//GEN-LAST:event_NewButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String query= "delete from CurrentUser;";
            stmt.executeUpdate(query);
            stmt.close();
            con.close();                      
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* gay */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoButton;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton NewButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
