/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class12
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StoreButton = new javax.swing.JButton();
        Instructions = new javax.swing.JButton();
        LevelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 237));
        setPreferredSize(new java.awt.Dimension(380, 237));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 219, 231));
        jLabel1.setText("MouseRun 2K17");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(76, 11, 222, 41);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 219, 231));
        jLabel4.setText("TM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(304, 11, 12, 14);

        StoreButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        StoreButton.setForeground(new java.awt.Color(1, 170, 193));
        StoreButton.setText("MouseStore");
        StoreButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 219, 231), 2));
        StoreButton.setContentAreaFilled(false);
        StoreButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StoreButton);
        StoreButton.setBounds(240, 80, 120, 45);

        Instructions.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        Instructions.setForeground(new java.awt.Color(1, 170, 193));
        Instructions.setText("Instructions");
        Instructions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 219, 231), 2));
        Instructions.setContentAreaFilled(false);
        Instructions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsActionPerformed(evt);
            }
        });
        getContentPane().add(Instructions);
        Instructions.setBounds(130, 140, 110, 45);

        LevelButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        LevelButton.setForeground(new java.awt.Color(1, 170, 193));
        LevelButton.setText("LevelSelect");
        LevelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 219, 231), 2));
        LevelButton.setContentAreaFilled(false);
        LevelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LevelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LevelButton);
        LevelButton.setBounds(20, 80, 110, 45);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark-blue-polygonal-background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 380, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreButtonActionPerformed
        // TODO add your handling code here:
        new Shop().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_StoreButtonActionPerformed

    private void InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsActionPerformed
        // TODO add your handling code here:
        new Instructions().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_InstructionsActionPerformed

    private void LevelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelButtonActionPerformed
        // TODO add your handling code here:
        new LevelSelect().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_LevelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instructions;
    private javax.swing.JButton LevelButton;
    private javax.swing.JButton StoreButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
