
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class12
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordField = new javax.swing.JPasswordField();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NewButton = new javax.swing.JButton();
        ConPassField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(380, 340));
        setMinimumSize(new java.awt.Dimension(380, 340));
        setPreferredSize(new java.awt.Dimension(380, 340));
        getContentPane().setLayout(null);

        PasswordField.setBackground(new java.awt.Color(255, 51, 51));
        PasswordField.setForeground(new java.awt.Color(56, 24, 69));
        PasswordField.setOpaque(false);
        getContentPane().add(PasswordField);
        PasswordField.setBounds(147, 136, 210, 29);

        NameField.setBackground(new java.awt.Color(255, 51, 51));
        NameField.setForeground(new java.awt.Color(56, 24, 69));
        NameField.setOpaque(false);
        getContentPane().add(NameField);
        NameField.setBounds(147, 80, 210, 28);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 24, 69));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 81, 39, 21);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 24, 69));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 137, 63, 21);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 24, 69));
        jLabel1.setText("NewMouse");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(102, 11, 146, 40);

        NewButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        NewButton.setForeground(new java.awt.Color(56, 24, 69));
        NewButton.setText("Create New Account");
        NewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(56, 24, 69), 2));
        NewButton.setContentAreaFilled(false);
        NewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewButton);
        NewButton.setBounds(80, 240, 220, 50);

        ConPassField.setBackground(new java.awt.Color(255, 51, 51));
        ConPassField.setForeground(new java.awt.Color(56, 24, 69));
        ConPassField.setOpaque(false);
        getContentPane().add(ConPassField);
        ConPassField.setBounds(147, 193, 210, 29);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 24, 69));
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 194, 119, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_polygonal_background.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 370, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButtonActionPerformed
        // TODO add your handling code here:
        String name= NameField.getText();
        String pass= new String(PasswordField.getPassword());
        String conpass= new String(ConPassField.getPassword());
        if(pass.equals(conpass))
        {   try
            {   Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
                Statement stmt= con.createStatement();
                String query= "insert into LoginForm values('"+name+"', '"+pass+"', 1, 0, 'N', 'N');";
                System.out.println(query);
                stmt.executeUpdate(query);
                con.close();
                stmt.close();
                JOptionPane.showMessageDialog(null, "Mouse generated.");
                new Login().setVisible(true);
                this.dispose();
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null, e);
            }
        }
        else
        {   JOptionPane.showMessageDialog(null, "Nigga u blind?");
        }
        
    }//GEN-LAST:event_NewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConPassField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton NewButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
