
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author class12
 */
public class Shop extends javax.swing.JFrame {

    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SkinGroup = new javax.swing.ButtonGroup();
        Buffer = new javax.swing.JTextField();
        Skin2 = new javax.swing.JTextField();
        Skin3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Buy1 = new javax.swing.JButton();
        Buy2 = new javax.swing.JButton();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        MoneyField = new javax.swing.JLabel();
        Mouse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(730, 480));
        setPreferredSize(new java.awt.Dimension(730, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 100, 159));
        jLabel1.setText("MouseStore");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(286, 11, 161, 41);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(151, 236, 197)), "MouseSkins", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 0, 18), new java.awt.Color(0, 100, 159))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setOpaque(false);

        Buy1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        Buy1.setForeground(new java.awt.Color(0, 100, 159));
        Buy1.setText("Buy");
        Buy1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 100, 159), 2));
        Buy1.setContentAreaFilled(false);
        Buy1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy1ActionPerformed(evt);
            }
        });

        Buy2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        Buy2.setForeground(new java.awt.Color(0, 100, 159));
        Buy2.setText("Buy");
        Buy2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 100, 159), 2));
        Buy2.setContentAreaFilled(false);
        Buy2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buy2ActionPerformed(evt);
            }
        });

        SkinGroup.add(RB1);
        RB1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RB1.setForeground(new java.awt.Color(0, 100, 159));
        RB1.setText("Default");
        RB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB1.setOpaque(false);
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });

        SkinGroup.add(RB2);
        RB2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RB2.setForeground(new java.awt.Color(0, 100, 159));
        RB2.setText("Cool");
        RB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB2.setOpaque(false);
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });

        SkinGroup.add(RB3);
        RB3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RB3.setForeground(new java.awt.Color(0, 100, 159));
        RB3.setText("CoolStar");
        RB3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB3.setOpaque(false);
        RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 170, 193));
        jLabel2.setText("Cost: 25000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 170, 193));
        jLabel3.setText("Cost: 100000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RB1)
                        .addGap(0, 227, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB2)
                            .addComponent(RB3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Buy1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(Buy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(RB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buy1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buy2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB3)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(27, 64, 345, 180);

        MenuButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(0, 100, 159));
        MenuButton.setText("Menu");
        MenuButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 100, 159), 3, true));
        MenuButton.setContentAreaFilled(false);
        MenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MenuButton);
        MenuButton.setBounds(181, 351, 354, 70);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 100, 159));
        jLabel10.setText("Points:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(169, 269, 74, 38);

        MoneyField.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        MoneyField.setForeground(new java.awt.Color(0, 100, 159));
        MoneyField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(151, 236, 197), 2));
        getContentPane().add(MoneyField);
        MoneyField.setBounds(307, 269, 232, 38);

        Mouse.setBackground(new java.awt.Color(255, 255, 255));
        Mouse.setToolTipText("");
        Mouse.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MouseComponentShown(evt);
            }
        });
        getContentPane().add(Mouse);
        Mouse.setBounds(510, 90, 110, 124);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/congruent_pentagonBIGG.png"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(719, 444));
        jLabel4.setPreferredSize(new java.awt.Dimension(719, 144));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 720, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void MouseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MouseComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MouseComponentShown

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
        // TODO add your handling code here:
        if(RB2.isSelected()==true)
        {   Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Cool Jerry(Green).png")); 
        }
        String skin2="";
        String user= Buffer.getText();
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from LoginForm where MouseID='"+user+"';";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {   skin2= rs.getString("skin3");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
        if(skin2.matches("Y"))
        {   try
            {   Connection conn= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
                Statement stmts = conn.createStatement();
                String bhaiya= "update LoginForm set skin=2 where MouseID='"+user+"';";
                stmts.executeUpdate(bhaiya);
                stmts.close();
                conn.close();
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e);
            }
        }        
        
    }//GEN-LAST:event_RB2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String behen= "select * from CurrentUser;";
            ResultSet rs= stmt.executeQuery(behen);
            String op="a";
            while(rs.next())
            {    op= rs.getString("MouseID");           
            }
            Buffer.setText(op);
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
        String user=Buffer.getText();
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from LoginForm where MouseID='"+user+"';";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {   int points= rs.getInt("points");
                MoneyField.setText(""+points);
                int skin=rs.getInt("skin");
                if(skin==1)
                {   RB1.setSelected(true);
                    Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\smol Jerry(Green).png"));                    
                }
                else if(skin==2)
                {   RB2.setSelected(true);
                    Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Cool Jerry(Green).png")); 
                }
                else if(skin==3)
                {   RB3.setSelected(true);
                    Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Slim(Green).png")); 
                }                     
                String skin2= rs.getString("skin2");
                System.out.println("Skin2: "+skin2);
                if(skin2.matches("Y"))
                {   Buy1.setEnabled(false);
                    Buy1.setVisible(false);
                }
                String skin3= rs.getString("skin3");
                System.out.println("Skin3: "+skin3);
                if(skin3.matches("Y"))
                {   Buy2.setEnabled(false);
                    Buy2.setVisible(false);
                }                      
            }
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB3ActionPerformed
        // TODO add your handling code here:
        if(RB3.isSelected()==true)
        {   Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Slim(Green).png")); 
        }
        String skin3="";
        String user= Buffer.getText();
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from LoginForm where MouseID='"+user+"';";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {   skin3= rs.getString("skin3");
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
        if(skin3.matches("Y"))
        {   try
            {   Connection conn= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
                Statement stmts = conn.createStatement();
                String bhaiya= "update LoginForm set skin=3 where MouseID='"+user+"';";
                stmts.executeUpdate(bhaiya);
                stmts.close();
                conn.close();
            }
         catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e);
            }
        }
        
    }//GEN-LAST:event_RB3ActionPerformed

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
        // TODO add your handling code here:
        if(RB1.isSelected()==true)
        {   Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\smol Jerry(Green).png")); 
        }
        String user=Buffer.getText();
        try
        {   Connection conn= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmts = conn.createStatement();
            String bhaiya= "update LoginForm set skin=1 where MouseID='"+user+"';";
            stmts.executeUpdate(bhaiya);
            stmts.close();
            conn.close();
        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_RB1ActionPerformed

    private void Buy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy1ActionPerformed
        // TODO add your handling code here:
        String user=Buffer.getText();
        int points=0;
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from LoginForm where MouseID='"+user+"';";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {   points= rs.getInt("points");                                                   
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);
        }
        if(points>25000)
        {   try
            {   Connection conn= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
                Statement stmts = conn.createStatement();
                String bhaiya= "update LoginForm set skin=2 where MouseID='"+user+"';";
                stmts.executeUpdate(bhaiya);
                bhaiya="update LoginForm set points="+(points-25000)+" where MouseID='"+user+"';";
                MoneyField.setText(""+(points-25000));
                stmts.executeUpdate(bhaiya);
                bhaiya="update LoginForm set skin2='Y' where MouseID='"+user+"';";
                stmts.executeUpdate(bhaiya);
                JOptionPane.showMessageDialog(null, "Your purchase is successful. ");
                Buy1.setEnabled(false);
                RB2.setSelected(true);
                Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Cool Jerry(Green).png")); 
                stmts.close();
                conn.close();
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e);
            }
        }
        else
        {   JOptionPane.showMessageDialog(null, "Insufficient funds available. Earn it to burn it.");
        }        
        
    }//GEN-LAST:event_Buy1ActionPerformed

    private void Buy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buy2ActionPerformed
        // TODO add your handling code here:
        String user=Buffer.getText();
        int points=0;
        try
        {   Connection con= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
            Statement stmt = con.createStatement();
            String bhai= "select * from LoginForm where MouseID='"+user+"';";
            ResultSet rs= stmt.executeQuery(bhai);
            while(rs.next())
            {   points= rs.getInt("points");                                                   
            }
            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        if(points>100000)
        {   try
            {   Connection conn= DriverManager.getConnection ("jdbc:mysql://localhost:3306/CatAndMouse", "root", "");
                Statement stmts = conn.createStatement();
                String bhaiya= "update LoginForm set skin=2 where MouseID='"+user+"';";
                stmts.executeUpdate(bhaiya);
                bhaiya="update LoginForm set points="+(points-100000)+" where MouseID='"+user+"';";
                MoneyField.setText(""+(points-100000));
                stmts.executeUpdate(bhaiya);
                bhaiya="update LoginForm set skin2='Y' where MouseID='"+user+"';";
                stmts.executeUpdate(bhaiya);
                JOptionPane.showMessageDialog(null, "Your purchase is successful. ");
                Buy1.setEnabled(false);
                RB2.setSelected(true);
                Mouse.setIcon(new ImageIcon("C:\\Users\\class12\\Documents\\NetBeansProjects\\CatAndMouse\\src\\Slim(Green).png")); 
                stmts.close();
                conn.close();
            }
            catch(Exception e)
            {   JOptionPane.showMessageDialog(null,e);
            }
        }
        else
        {   JOptionPane.showMessageDialog(null, "Insufficient funds available. Earn it to burn it.");
        }
        
    }//GEN-LAST:event_Buy2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buffer;
    private javax.swing.JButton Buy1;
    private javax.swing.JButton Buy2;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel MoneyField;
    private javax.swing.JLabel Mouse;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JTextField Skin2;
    private javax.swing.JTextField Skin3;
    private javax.swing.ButtonGroup SkinGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
